### ISSUE TITLE
DBT run command is sometimes ran before venv is activated

### ISSUE THREAD

**Issue by camfrout** [innoverio/vscode-dbt-power-user#24]
Hi,

In the latest version, a `cd` command is sent to the terminal but it fails when the path contains some spaces.
https://github.com/innoverio/vscode-dbt-power-user/blob/f7749f2b5c462eb105d10295b4f126491ac6b70a/src/commands/runModel.ts#L45

It should be a quick fix by surrounding the path with single or double-quotes.

**Comment by mdesmet** [comment]
I removed the cd command as there is an option to set the cwd when launching the terminal.

Also we will always open a new terminal as potentially the path of the existing terminal might be wrong. When your venv is correctly setup through vscode-python extension, it should execute the command after the venv initialization.

Can you let us know if it works for you?

**Comment by camfrout** [comment]
Hi. With the new behaviour, unfortunately, the terminal runs the command `dbt run --model xxxx` before it activates the virtual environment, so it fails.

I have correctly set up a Python Interpreter though.

On that note, is there a way to check the current PATH of the terminal from an extension and only create a new terminal if we are not in the correct folder? If a new terminal is started every time I press the play button I am not super keen on having dozens of terminal created. (I personally prefer much more the option to run in the current one)

**Comment by mdesmet** [comment]
There seems no way in the vscode api to retrieve information about what's happening in a terminal. However we will look into supporting tasks (compilation, running models, ....) soon, that might give us other ways of reusing terminals (read only) for executing such commands.

I just looked at the code I refactored today and realized that i reintroduced the issue about venv activation. I fixed that by putting a delay after the terminal creation, in order for the javascript event loop to execute the handlers on the terminal creation in the vscode-python plugin before executing the dbt command. However if i do the delay before the terminal creation that would not work of course...

We will fix this in 0.3.4. Can you retest?

**Comment by camfrout** [comment]
Thanks for the answer!
I am using 0.3.5 now and it still doesn't work.  Same as before, it tries to do a `dbt run` before the venv is activated.

```
Microsoft Windows [Version 10_______]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\xxxxx>C:/Users/xxxx/anaconda3/Scripts/activate

(base) C:\Users\xxxxx>dbt run --model my_model
'dbt' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\xxxxx>conda activate myvenv

(myvenv) C:\Users\xxxxx>
```

Another use case where I wouldn't like to run a new terminal as well is that, in Windows, I can run `wsl` (Windows System for Linux) in a terminal and have a fully functioning Linux shell (it even works with ZSH). Every new terminal that is created will be a  basic Windows one, not a Linux one.

So, in my personal use cases of dbt and this extension, I would always prefer to have the dbt command running in the current terminal.

If there are genuine reasons to run a new terminal every time, could this then be a global extension option to either run the command in the current terminal or a new one?

**Comment by mdesmet** [comment]
![venv](https://user-images.githubusercontent.com/9265503/93374557-28e28b00-f857-11ea-8442-2368877451ac.gif)

Do you follow the same process as I'm doing above?

I'm actually using mostly wsl2 for running dbt on linux, it works fine through the vscode remoting. I would assume it works similar as in the screenshot above (that's on windows + venv). I am just using latest committed code.

I will review the PR and can probably merge it, but not sure we can keep the functionality when we move this to vscode tasks (see #19 ).

**Comment by mdesmet** [comment]
It has been merged and released (0.3.6)

**Comment by camfrout** [comment]
Hi!
I am following the same steps, yes. 

I have been able to drill down a bit into the issue:

1. If my default shell is "Command prompt", the `conda activate` command is always typed after the `dbt run`
2. If my default shell is "Powershell", the `conda activate` command is sometimes typed before the `dbt run` (and in that case the command runs correctly), and sometimes it is typed after and fails. It seems to randomly be typed before and after.

**Comment by mdesmet** [comment]
To summarize our issue is that we currently have no reliable way to schedule a command after the vscode-python has activated the venv. I actually looked into their code and they trigger the venv activation through the onDidOpenTerminal: Event<Terminal>event. We could of course increase the delay but that's obviously not super reliable.

Needs some more digging to see what can be done.
