### ISSUE TITLE
Model Graph 

### ISSUE THREAD

**Issue by jarodam** [innoverio/vscode-dbt-power-user#45]
Hello, 
Thanks for the plugin! It looks like the model graph doesn't acknowledge that the parent or child of a model can be a snapshot or that the snapshot can begin a graph.
To repro:
Create a snapshot of an existing model.
Create a new model that references that snapshot.

In all three (the existing model, snapshot, and snapshot-dependant model), attempt to view the model.

**Comment by mdesmet** [comment]
I need to check how this is persisted in the manifest and make appropriate changes. We don't use the snapshot feature in our projects.

**Comment by mdesmet** [comment]
HI @jarodam ,

I've released a new version to support snapshots (0.4.7). Autocomplete, definition and graph should be supported.

Let me know if it works for you.

**Comment by jarodam** [comment]
Hi @mdesmet That's awesome and fast! 

I looked at existing models without snapshots to see it still works as expected. Didn't do an exhaustive look but it did appear to work. 

However, when I click on a model that has a snapshot up or downstream, I get the following error:

Cannot read property 'replace' of undefined

I updated it and I've tried uninstalling and re-installing but the same.

**Comment by mdesmet** [comment]
That's interesting, from a graph perspective actually there's actually no difference between a model or a snapshot. 

I have replicated the situation over here and snapshots seems to work, both down- or upstream.

Could you attach your manifest file if it's not sensitive? Also which platform are you using (win-mac-linux)?

**Comment by jarodam** [comment]
this is on windows. I cannot attach the manifest, unfortunately.  I did put in more time troubleshooting this AM. It looks like the issue with references being to a source:
{{ source('source_database','sourceTable') }}

When I comment out the line above and replace it with a hardcoded value or other ref, it works. When I change the source to another source it still fails.

**Comment by jarodam** [comment]
Just in case, the syntax isn't clear from above, here is the DBT link : https://docs.getdbt.com/reference/dbt-jinja-functions/source

**Comment by mdesmet** [comment]
Well, everything in the end comes down to a source, unless we are hardcoding them. I obviously also have sources in the model graph of my snapshots and it worked for me. I will need more details to be able to reproduce the issue.

You could try to enable the console through Help > Toggle developer tools to see if there is any more info there?

**Comment by jarodam** [comment]
sure. Happy to help. This is the output from dev tools:
[Extension Host] Text: {{, number: 123, hex=007B
console.ts:137 [Extension Host] Text: to, number: 116, hex=0074
notificationsAlerts.ts:38 TypeError: Cannot read property 'replace' of undefined
	at Function.file (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:157:279)
	at new v (c:\Users\Me\.vscode\extensions\innoverio.vscode-dbt-power-user-0.4.7\dist\extension.js:16:253946)
	at new E (c:\Users\Me\.vscode\extensions\innoverio.vscode-dbt-power-user-0.4.7\dist\extension.js:16:254089)
	at c:\Users\Me\.vscode\extensions\innoverio.vscode-dbt-power-user-0.4.7\dist\extension.js:16:253560
	at Array.map (<anonymous>)
	at i.getTreeItems (c:\Users\Me\.vscode\extensions\innoverio.vscode-dbt-power-user-0.4.7\dist\extension.js:16:253350)
	at i.getChildren (c:\Users\Me\.vscode\extensions\innoverio.vscode-dbt-power-user-0.4.7\dist\extension.js:16:253186)
	at m.fetchChildrenNodes (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:661:907)
	at m.getChildren (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:658:839)
	at t.ExtHostTreeViews.$getChildren (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:683)
	at m._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:892:926)
	at m._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:892:618)
	at m._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:891:252)
	at m._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:890:201)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:888:136
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:233:787)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1094:104
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:233:787)
	at t.PersistentProtocol._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:238:1004)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:235:927
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at p.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:231:195)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:230:547
	at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:822)
	at Socket.emit (events.js:223:5)
	at Socket.EventEmitter.emit (domain.js:475:20)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)

**Comment by mdesmet** [comment]
Based on the call stack the issue is in the instantiation in any of these classes. It seems unrelated to the usage of {{ source(...) }}. these are classes from vscode. I'm assuming you're on latest vscode?

https://github.com/innoverio/vscode-dbt-power-user/blob/1fd470a51bfafbb27fd385e4fc0ca6cb3012b7a2/src/treeview_provider/ModelTreeviewProvider.ts#L116-L122

**Comment by jarodam** [comment]
That's interesting. Yes, I believe I am on the latest version. 
I just checked for updates and it says there are none. 
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by jarodam** [comment]
Thank you for your help on this. Interestingly I can repro it with a clean file using ref (works) and source (doesn't work). 
Since I have the latest version of VSCode installed, I thought I would remove variables such as the age of dbt and python so I upgraded both and now the extension is working as expected. Thank you for this extension and your help with solving it. 

If others have a similar issue, try ensuring your python, dbt, vscode, and extension are the latest. So far, that seems to have worked for me.
